services:
  # Backend service
  - type: web
    name: dr-shopper-backend
    env: python
    plan: free
    buildCommand: cd Backend && pip install -r requirements.txt
    startCommand: cd Backend && python app.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: dr-shopper-db
          property: connectionString
    
  # Frontend service  
  - type: web
    name: dr-shopper-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: dr-shopper-db
    plan: free
