"""fix_category_self_reference

Revision ID: 5f0400322a28
Revises: 046fe0f0d717
Create Date: 2025-08-18 14:12:08.307131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f0400322a28'
down_revision = '046fe0f0d717'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('category_category_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'category', ['parent_id'], ['id'])
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('category_category_id_fkey'), 'category', ['category_id'], ['id'])
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###
