"""add email verification and reset password fields to user

Revision ID: 6f930b7e737a
Revises: 0c4b4e383c96
Create Date: 2025-07-03 17:51:47.460179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f930b7e737a'
down_revision = '0c4b4e383c96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('email_verification_token', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('reset_password_token', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('reset_password_token_expiration', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('reset_password_token_expiration')
        batch_op.drop_column('reset_password_token')
        batch_op.drop_column('email_verification_token')
        batch_op.drop_column('email_verified')

    # ### end Alembic commands ###
